version: '3.8'

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/event_system
      - SESSION_SECRET=changeme
      - SESSION_NAME=sid
      - ENCRYPTION_KEY=changemechangemechangemechangeme
      - SMTP_HOST=localhost
      - SMTP_PORT=1025
      - SMTP_SECURE=false
      - SMTP_USER=
      - SMTP_PASS=
      - EMAIL_FROM_NAME=Event System
      - EMAIL_FROM=no-reply@example.com
      - CORS_ORIGIN=http://localhost:5174
    ports:
      - "5000:5000"

volumes:
  mongo_data:


